[package]
name = "beacon_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^2.0.2",  features = ["std", "unstable" ] }
risc0-zkvm-platform = { version = "^2.0.2", features = ["sys-getenv"] }
z-core = { path = "../../core", default-features = false }
bincode = { version = "1.3" }
blst = { version = "0.3.14", default-features = false, features = ["no-threads"]}
risc0-bigint2 = { version = "=1.4.2", default-features = false, features = [
  "unstable",
] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "std", "fmt"] }


[patch."https://github.com/willemolding/ssz-rs"]
# ssz_rs = { path = "../../../ssz-rs/ssz-rs" }
ssz_rs = { git = "https://github.com/ec2/ssz-rs", rev = "86be2a71c2bd4d5b454a8e86b83af1effd1e14d8"}


[patch.crates-io]
blst = { git = "https://github.com/risc0/blst.git", tag = "v0.3.14-risczero.0" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.4-risczero.1" }