[package]
name = "chainspec"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = "Apache-2.0"


[features]
mainnet = []
testharness = []
sepolia = []

[dependencies]
z-core = { workspace = true }
