[package]
name = "chainspec"
version.workspace = true
edition.workspace = true
repository.workspace = true

[features]
mainnet = []
testharness = []
sepolia = []

[dependencies]
z-core = { workspace = true }
