[package]
name = "chainspec"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[features]
mainnet = []
sepolia = []

[dependencies]
beacon_types = { workspace = true, default-features = false, features = ["legacy-arith"] }
serde_yaml = "0.9"
