[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { workspace = true }
risc0-zkvm = { workspace = true, features = ["std", "unstable", "prove"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
anyhow = "1.0"
ssz_rs = { workspace = true, default-features = false, features = ["serde", "std"] }
ethereum-consensus = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
reqwest-eventsource = "0.6"
clap = { version = "4.0", features = ["derive", "env"] }
thiserror = "2.0.6"
serde_json = "1.0.133"
reqwest-middleware = "0.4.0"
http-cache-reqwest = "0.15.0"
url = { version = "2.5" }
tracing = { workspace = true }
tokio = { version = "1.35", features = ["full"] }
z-core = { path = "../core", default-features = false, features = ["host"] }
futures = { version = "0.3" }
beacon-api-client = { git = "https://github.com/gattaca-com/ethereum-consensus.git", rev = "072fb2c5abdc8585db5ea6136db561b733a56234" }
bincode = { workspace = true }
governor = "0.10"
async-trait = "0.1"
http = "1.3"
