[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
beacon-api-client = { git = "https://github.com/gattaca-com/ethereum-consensus.git", rev = "072fb2c5abdc8585db5ea6136db561b733a56234" }
bincode = { workspace = true }
clap = { version = "4.0", features = ["derive", "env"] }
ethereum-consensus = { workspace = true }
futures = { version = "0.3" }
governor = "0.10"
http = "1.3"
http-cache-reqwest = "0.15.0"
methods = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
reqwest-eventsource = "0.6.0"
reqwest-middleware = "0.4.0"
risc0-zkvm = { workspace = true, features = ["std", "unstable", "prove"] }
serde = "1.0"
serde_json = "1.0.133"
ssz_rs = { workspace = true, default-features = false, features = ["serde", "std"] }
thiserror = "2.0.6"
tokio = { workspace = true }
tracing =  { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2.5" }
z-core = { path = "../core", default-features = false, features = ["host"] }
z_core_test_utils = { package = "test_utils", path = "../core/test_utils" }
