[package]
name = "z-core"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = { workspace = true, default-features = false }
ssz_rs = { workspace = true, default-features = true, features = ["serde"] }
ethereum-consensus = { workspace = true, default-features = false, optional = true }
serde = { workspace = true }
tracing = "0.1.41"
serde_json = "1.0.133"
sha2 = { workspace = true, default-features = false }
anyhow = { workspace = true }
ssz-multiproofs = { path = "../ssz-multiproofs" }
thiserror = { workspace = true }
blst = { version = "0.3.14", default-features = false, features = ["serde"]}
serde_arrays = { version = "0.2.0" }
elsa = { version = "1.11", optional = true }

[features]
default = ["host"]
host = [
    "dep:ethereum-consensus", "ssz-multiproofs/builder", "blst/default", "ssz-multiproofs/progress-bar", "dep:elsa"
]
