[package]
name = "z-core"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = { workspace = true, default-features = false }
ssz_rs = { workspace = true, default-features = true, features = ["serde"] }
ethereum-consensus = { workspace = true, default-features = false, optional = true }
serde = { workspace = true }
tracing = "0.1.41"
serde_json = "1.0.133"
sha2 = { workspace = true, default-features = false }
anyhow = { workspace = true }
ssz-multiproofs = { path = "../ssz-multiproofs" }
thiserror = { workspace = true }
blst = { version = "0.3.14", default-features = false, features = ["serde"]}
serde_arrays = { version = "0.2.0" }
elsa = { version = "1.11", optional = true }

beacon_chain = { git = "https://github.com/sigp/lighthouse.git", rev = "7759cb8f91c01a7d335469d317b5787368656064", optional = true } 
beacon_types = { package = "types", git = "https://github.com/sigp/lighthouse.git", rev = "7759cb8f91c01a7d335469d317b5787368656064", optional = true } 

[dev-dependencies]
sloggers = "2.2.0"
tempfile = "3.20.0"
tokio = { workspace = true }
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }

[features]
default = ["host"]
host = [
    "dep:ethereum-consensus", "ssz-multiproofs/builder", "blst/default", "ssz-multiproofs/progress-bar", "dep:elsa", "dep:beacon_chain", "dep:beacon_types"
]
