[package]
name = "test_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
z-core = { path = ".." }

alloy-primitives = { workspace = true, default-features = false }
thiserror = { workspace = true }
elsa = { version = "1.11" }
ethereum-consensus = { workspace = true, default-features = false }
serde_json = "1.0.133"
anyhow = { workspace = true }
serde = { workspace = true }

beacon_chain = { git = "https://github.com/sigp/lighthouse.git", rev = "7759cb8f91c01a7d335469d317b5787368656064" } 
beacon_types = { package = "types", git = "https://github.com/sigp/lighthouse.git", rev = "7759cb8f91c01a7d335469d317b5787368656064" }
