[book]
authors = ["Boundless (beboundless.xyz)"]
language = "en"
multilingual = false
src = "src"
title = "The Signal: Ethereum"

[output.html]
mathjax-support = true

[preprocessor]

[preprocessor.katex]
after = ["links"]
