[book]
title = "The Signal: Ethereum"
authors = ["Boundless (beboundless.xyz)"]
language = "en"
multilingual = false

[preprocessor.katex]
after = ["links"]
# KaTeX options.
output = "htmlAndMathml"
fleqn = true
