name: main

on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RUST_BACKTRACE: "1"
  RISC0_RUST_TOOLCHAIN_VERSION: 1.88.0
  RISC0_VERSION: 2.3.0

jobs:
  test:
    runs-on: [ self-hosted, prod, "${{ matrix.os }}", "${{ matrix.arch }}", "${{ matrix.device }}" ]
    strategy:
      matrix:
        include:
          - os: Linux
            arch: X64
            feature: default
            device: cpu
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - name: checkout dummy commit (submodule bug workaround)
        run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"

      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust
        uses: risc0/risc0/.github/actions/rustup@fbe1d0bb75c21fe36cefd87bae25f424b711b291

      - name: Install sccache
        uses: boundless-xyz/boundless/.github/actions/sccache@main
        with:
          key: ${{ matrix.os }}-${{ matrix.feature }}

      - name: install cargo risczero
        uses: ./.github/actions/bininstall-risc0
        with:
          risczero-version: ${{ env.RISC0_VERSION }}
          toolchain-version: ${{ env.RISC0_RUST_TOOLCHAIN_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: run tests
        env:
            RISC0_DEV_MODE: true
        run: cargo test --locked

      - name: Show sccache stats
        run: sccache --show-stats

  lint:
    runs-on: [ self-hosted, prod, "${{ matrix.os }}", "${{ matrix.arch }}", "${{ matrix.device }}" ]
    strategy:
      matrix:
        include:
          - os: Linux
            arch: X64
            feature: default
            device: cpu
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          # Full history is required by license-check.py
          fetch-depth: 0
          submodules: recursive

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install rust
        uses: risc0/risc0/.github/actions/rustup@fbe1d0bb75c21fe36cefd87bae25f424b711b291

      - name: Install sccache
        uses: boundless-xyz/boundless/.github/actions/sccache@main
        with:
          key: ${{ matrix.os }}-${{ matrix.feature }}

      - name: license check
        run: python license-check.py

      - name: lint rust code
        run: cargo fmt --all --check

      - name: cargo clippy
        env:
          RUSTFLAGS: "-Dwarnings"
          RISC0_SKIP_BUILD: 1
        run: cargo clippy --all --locked

      - name: lint guest code
        working-directory: methods/guest
        run: cargo fmt --all --check

      - name: Show sccache stats
        run: sccache --show-stats

  build-docker:
    runs-on: [ self-hosted, prod, "${{ matrix.os }}", "${{ matrix.arch }}", "${{ matrix.device }}" ]
    strategy:
      matrix:
        include:
          - os: Linux
            arch: X64
            feature: default
            device: cpu
    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust
        uses: risc0/risc0/.github/actions/rustup@fbe1d0bb75c21fe36cefd87bae25f424b711b291

      - name: Install sccache
        uses: boundless-xyz/boundless/.github/actions/sccache@main
        with:
          key: Linux-default

      - name: install cargo risczero
        uses: ./.github/actions/bininstall-risc0
        with:
          risczero-version: ${{ env.RISC0_VERSION }}
          toolchain-version: ${{ env.RISC0_RUST_TOOLCHAIN_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build guest with docker
        env:
          RISC0_USE_DOCKER: 1
        run: cargo build --manifest-path=methods/Cargo.toml 
